.\" $Id: JAM_ReadLastRead.3,v 1.1 2002/11/09 00:37:16 raorn Exp $
.\"
.TH JAM_ReadLastRead 3 2002-11-07 "" "JAM subroutine library"
.SH NAME
JAM_ReadLastRead \- Read a lastread record
.SH SYNOPSIS
.nf
.B #include <jamlib/jam.h>

.BI "int JAM_ReadLastRead(s_JamBase*     " Base_PS ","
.BI "                     ulong          " User_I ","
.BI "                     s_JamLastRead* " Record_PS ");"
.RE
.fi
.SH DESCRIPTION
Reads a lastread record from the lastread file.
.SS Arguments
.TP
.I Base_PS
The message base to use
.TP
.I User_I
A system\-unique user number.
.TP
.I Record_PS
A pointer to the lastread struct where the record will be stored.
.SH "RETURN VALUE"
.TP
.B 0
if successful
.TP
.B JAM_IO_ERROR
if an I/O error occured. See
.BR JAM_Errno (3)
.TP
.B JAM_BAD_PARAM
if Record_PS is NULL
.TP
.B JAM_NO_USER
if the user number was not found
.SH EXAMPLES
.nf
int           Result_I;
s_JamLastRead LastRead_S;

Result_I = JAM_ReadLastRead( Base_PS, 4711, &LastRead_S);
if (Result_I)
  printf("JAM_ReadLastRead returned %d\\n", Result_I);
.fi
.SH AUTHOR
This manual page was created by Sir Raorn <raorn@altlinux.ru>,
based on original JAMlib documentation by Bjorn Stenberg
<bjorn@haxx.nu> and Johan Billing <billing@df.lth.se>.
.SH SEE ALSO
.BR jamlib (3),
.BR JAM_WriteLastRead (3)
.BR JAM_Errno (3)
.\" vim: ft=nroff
