.\" $Id: JAM_AddEmptyMessage.3,v 1.1 2002/11/09 00:37:16 raorn Exp $
.\"
.TH JAM_AddEmptyMessage 3 2002-11-07 "" "JAM subroutine library"
.SH NAME
JAM_AddEmptyMessage \- Add a empty message entry to a message base
.SH SYNOPSIS
.nf
.B #include <jamlib/jam.h>

.BI "int JAM_AddEmptyMessage(s_JamBase*      " Base_PS ");"
.RE
.fi
.SH DESCRIPTION
Adds an empty message header to the message base. Useful when writing a
messagebase maintenance utility.
.SS Arguments
.TP
.I Base_PS
The message base to use
.SH "RETURN VALUE"
.TP
.B 0
if successful
.TP
.B JAM_IO_ERROR
if an I/O error occured. See
.BR JAM_Errno (3)
.TP
.B JAM_NOT_LOCKED
if the message base is not locked
.SH AUTHOR
This manual page was created by Sir Raorn <raorn@altlinux.ru>,
based on original JAMlib documentation by Bjorn Stenberg
<bjorn@haxx.nu> and Johan Billing <billing@df.lth.se>.
.SH SEE ALSO
.BR jamlib (3),
.BR JAM_AddMessage (3),
.BR JAM_LockMB (3),
.BR JAM_Errno (3)
.\" vim: ft=nroff
