.\" $Id: JAM_ClearMsgHeader.3,v 1.1 2002/11/09 00:37:16 raorn Exp $
.\"
.TH JAM_ClearMsgHeader 3 2002-11-07 "" "JAM subroutine library"
.SH NAME
JAM_ClearMsgHeader \- Clear a message header structure
.SH SYNOPSIS
.nf
.B #include <jamlib/jam.h>

.BI "int JAM_ClearMsgHeader(s_JamMsgHeader* " Header_PS ");"
.RE
.fi
.SH DESCRIPTION
Clears a message header structure and prepares it for use. This
includes setting \fISignature\fP and \fIRevision\fP fields to
their correct values, and setting CRC fields to \fBJAM_NO_CRC\fP.
.SS Arguments
.TP
.I Header_PS
A pointer to the structure to prepare.
.SH "RETURN VALUE"
.TP
.B 0
if successful
.TP
.B JAM_BAD_PARAM
if Header_PS is NULL
.SH AUTHOR
This manual page was created by Sir Raorn <raorn@altlinux.ru>,
based on original JAMlib documentation by Bjorn Stenberg
<bjorn@haxx.nu> and Johan Billing <billing@df.lth.se>.
.SH SEE ALSO
.BR jamlib (3),
.BR JAM_ReadMsgHeader (3),
.BR JAM_ChangeMsgHeader (3)
.\" vim: ft=nroff
