.\" $Id: JAM_CloseMB.3,v 1.1 2002/11/09 00:37:16 raorn Exp $
.\"
.TH JAM_CloseMB 3 2002-11-07 "" "JAM subroutine library"
.SH NAME
JAM_CloseMB \- Close message base
.SH SYNOPSIS
.nf
.B #include <jamlib/jam.h>

.BI "int JAM_CloseMB(s_JamBase* " Base_PS ");"
.RE
.fi
.SH DESCRIPTION
Unlocks (if locked) and closes the currently open message base.
.SS Arguments
.TP
.I Base_PS
The message base to close. Note, that you must
.BR free (3)
this memory upon successful messagebase closing.
.SH "RETURN VALUE"
.TP
.B 0
if successful
.TP
.B JAM_IO_ERROR
if an I/O error occured. see
.BR JAM_Errno (3)
.TP
.B JAM_LOCK_FAILED
if the message base could not be unlocked
.PP
.SH EXAMPLES
.nf
int Result_I;

Result_I = JAM_CloseMB(Base_PS);
if ( Result_I )
  printf("JAM_CloseMB returned %d.\\n", Result_I);
.fi
.SH AUTHOR
This manual page was created by Sir Raorn <raorn@altlinux.ru>,
based on original JAMlib documentation by Bjorn Stenberg
<bjorn@haxx.nu> and Johan Billing <billing@df.lth.se>.
.SH SEE ALSO
.BR jamlib (3),
.BR JAM_OpenMB (3),
.BR JAM_CreateMB (3),
.BR JAM_Errno (3)
.\" vim: ft=nroff
